### ISSUE TITLE
Add proper URL to the GitHub project

### ISSUE THREAD

**Issue by davidak** [NixOS/mobile-nixos-website#3]
and README

right now you can't click it, it's just the domain :(

![Screenshot from 2020-01-26 21-28-27](https://user-images.githubusercontent.com/91113/73141294-e2031380-4082-11ea-8298-ac40232d4816.png)

**Comment by samueldr** [comment]
I don't have the rights to edit the metadata for the repository.

Though yes, it should be done. Thanks.

**Comment by grahamc** [comment]
Updated.

**Comment by samueldr** [comment]
Thanks you very much!
