### ISSUE TITLE
Github action is no longer running because "there hasn't been activity in this repository for at least 60 days"

### ISSUE THREAD

**Issue by kyelewis** [NixOS/mobile-nixos-website#9]
"This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs."

There are some options in the Mobile NixOS options that are now out of date.

Can someone from the project kick off the workflow again? @samueldr ?

**Comment by samueldr** [comment]
Thanks for noticing and notifying.

Blargh! It's so annoying that the action gets disabled because it's "unused" (the site hasn't changed), and then requires kicking the wheels for no good reason.

It should now be updating again.

**Comment by samueldr** [comment]
[it did update](https://github.com/NixOS/mobile-nixos-website/commit/7f8a133875bcc83ed64b4934e221fde53d6fe52d)
